[role="xpack"]
[[workflow]]
== The {ml} workflow

Before you dive into the details of the {stack} {ml-features}, it's a good idea
to understand the big picture. There are many types of analysis, which can help
you solve many different types of problems. By taking the time to plan in
advance, you get the best possible results.

. Define the problem you want to solve.

. Construct your data set.

. (Optional) Transform your data.

. Train a model.

. (Optional) Evaluate your model.

. Use the model to make predictions.

[discrete]
=== Define the problem

The first consideration, especially when you are first learning to use {ml},
is the importance of the data and how familiar you are with it. Ideally, it is
information that contains key performance indicators (KPIs) for the health,
security, or success of your business or system. It is information that you need
to monitor and act on when anomalous behavior occurs. You might even have {kib}
dashboards that you're already using to watch this data. The better you know the
data, the quicker you will be able to create {ml-jobs} that generate useful
insights.

The second consideration is what type of analysis you want to perform. The
{ml-features} provide both <<xpack-ml,{anomaly-detect}>> and
<<ml-dfanalytics,{dfanalytics}>>.

[discrete]
=== Prepare your data

IMPORTANT: If you want to create {anomaly-jobs} in {kib}, you must use {dfeeds}.
That is to say, you must store your input data in {es}. When you create
a job, you select an existing index pattern and {kib} configures the {dfeed}
for you under the covers.

If your data is outside of {es}, {anomaly-detect} is still possible by using the
{ref}/ml-post-data.html[post data to jobs API].

