[role="xpack"]
[[workflow]]
== The {ml} workflow

Before you dive into the details of the {stack} {ml-features}, it's a good idea
to understand the big picture. There are many types of analysis, which can help
you solve many different types of problems. By taking the time to plan in
advance, you get the best possible results.

. <<workflow-define,Define the problem>>.

. <<workflow-prepare,Prepare your data>>.

. Train a model.

. (Optional) Evaluate your model.

. Use the model to make predictions.

[discrete]
[[workflow-define]]
=== Define the problem

Think about the problem you want to solve. Write down the questions you want
to answer. For example, are you trying to predict whether a customer will renew
a subscription or whether a specific package will be delivered on time? Do you
want to find outliers or anomalous behavior in your data?

Your problem statement affects which type of data you require and which types of
{ml} analysis are applicable.  

[discrete]
[[workflow-prepare]]
=== Prepare your data

Once you've identified the problem, consider which data is necessary to solve it.

////
Typically, the most useful {anomaly-detect} results come from data sets that
contain key performance indicators (KPIs) for the health, security, or success
of your business or system. You might even have {kib} dashboards that you're
already using to watch this data. It is important to be familiar with your data
so that you 


IMPORTANT: If you want to create {anomaly-jobs} in {kib}, you must use {dfeeds}.
That is to say, you must store your input data in {es}. When you create
a job, you select an existing index pattern and {kib} configures the {dfeed}
for you under the covers.

If your data is outside of {es}, {anomaly-detect} is still possible by using the
{ref}/ml-post-data.html[post data to jobs API].
////
